version: '3.3'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=spotNfse
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - 5435:5432
volumes:
  postgres-data:
